on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        default: 'Ghadeero'
        required: true
  
name: CI

jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, ${{ github.event.inputs.name }}"
